server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

user-service:
  url: http://localhost:8080


appDescription: "Pragma Powerup"
appVersion: "1.0.0"
