server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: TRACE
        web: DEBUG


jwt:
  secret: "5qaPrnb5CYNQqH3WkaNX6ZZZEBMbftqrhxyv0tPMk1Xwjq6kgHNehigwIabVg/JWZ3ekmkhH2QSnY406SdnPSA=="
  expiration: 3600000

user-service:
  url: http://localhost:8080

messaging-service:
  url: http://localhost:8082

traceability-service:
  url: http://localhost:8083


appDescription: "Pragma Powerup"
appVersion: "1.0.0"
